### ISSUE TITLE
Failed to call "forward" method in function 'forward'

### ISSUE THREAD

**Issue by rmorros** [ashukid/hed-edge-detector#1]
Thanks for the code!
When I try it, I get an error:

$python edge_detector.py --input ima.jpg --prototxt deploy.prototxt --caffemodel hed_pretrained_bsds.caffemodel --width 300 --height 300
Traceback (most recent call last):
  File "edge_detector.py", line 63, in <module>
    out = net.forward()
cv2.error: OpenCV(4.0.0) /Users/travis/build/skvark/opencv-python/opencv/modules/dnn/misc/python/pyopencv_dnn.hpp:163: error: (-213:The function/feature is not implemented) Failed to call "forward" method in function 'forward'

I have tried in two different environments: 
1)Mac OSX, virtualenv with python 3.6, OpenCV installed as: pip install opencv-contrib-python (python 4.0.0)
2) Ubuntu, virtualenv with python 3.6, OpenCV installed as: pip install opencv-contrib-python==3.4.5.20

In both cases I get the same error. Any ideas on how to solve this?
Thanks!

**Comment by janithwanni** [comment]
For anyone having this issue right now,
this PR might help them out.
[Link](https://github.com/opencv/opencv/pull/13600)

**Comment by ashukid** [comment]
This issue has been solved by @janithwanni
